### PR TITLE
Fix default value of 0 in a type="number" Text field

### PR DESCRIPTION
**Pull request by avrahams1**
Fixed default value of 0 in a type="number" Text field
Added cross-env for Windows build
Added example of fix in FormsWithArrays.js file - field "numberField"
#247

### CODE REVIEW

**Comment by avrahams1** [comment]
The build error doesn't seem to have anything to do with my commit, I haven't touched anything relating SASS or Webpack...

**Comment by joepuzzo** [comment]
Can you undo the modification to the docs? Im sure you just used it to exploratory test but it has nothing to do with the array examples.

**Comment by avrahams1** [comment]
Done, pushed the change :)
Anything else?

**Comment by joepuzzo** [comment]
Yes what is the cross-env stuff you added?

**Comment by avrahams1** [comment]
The project as it was configured would only compile on linux based systems (ubuntu, mac OS..), since on WIndows there's a different way to define environment variables, the package.json npm commands didn't work on Windows as they were written.
For example:
`"start": "NODE_ENV=development webpack-dev-server -d --config config/webpack/webpack.dev.config.js --port 4005 --hot"`

This line works on Linux based systems, it defines an environment variable called NODE_ENV with a value of "development" then calls webpack.
On Windows you'd have to write:
`"start": "SET NODE_ENV=development webpack-dev-server -d --config config/webpack/webpack.dev.config.js --port 4005 --hot"`

That's why cross-env exists, it gives you one unified way of defining environment variables in the NPM commands for both systems.
So the "cross platform" way of writing the command is this:

`"start": "cross-env NODE_ENV=development webpack-dev-server -d --config config/webpack/webpack.dev.config.js --port 4005 --hot"`

**Comment by joepuzzo** [comment]
ok cool i have learned something new haha

**Comment by avrahams1** [comment]
Glad to have been of help :)

So is everything else okay?
Are you going to merge the changes and deploy a new version to NPM?

**Comment by joepuzzo** [comment]
You forgot to include it as a dev dep.. i added it. Dont forgett to save to package.json haha

**Comment by joepuzzo** [comment]
This is now in the latest release

**Comment by avrahams1** [comment]
I did add cross-env to devDependencies :)
Check the changes in my commits

**Comment by joepuzzo** [comment]
No i did it

**Pull request merged**
