### PR TITLE
Add a DefaultValue prop

### PR DESCRIPTION
**Pull request by SebastiaanNijland**
This allows for a DefaultValue to be passed to text inputs

### CODE REVIEW

**Comment by joepuzzo** [comment]
So I don't think this does what you think it does. The problem with doing this is that the react formApi will not actually register that you set that default value. If you tried to log the `formApi.values` without touching anything, you would actually get `{}` in the logs. The reason it has the `|| ''`is to mitigate an issue where react will throw an uncontrolled input error. I would recomend using the `defaultValues` prop on the form.

**Comment by hnq90** [comment]
I agree. We should use defaultValues for form initialization.

**Comment by SebastiaanNijland** [comment]
Ah yes, I hadn't seen that option. Is it possible to open-source the docs, so the community can add to it?

**Comment by joepuzzo** [comment]
The docs are open sourced. They live right in this project. And default values are already documented :)

**Pull request closed without merging**
