### PR TITLE
fix: field `defaultValue` should precedence over form `defaultValues`

### LINKED ISSUE #435: [Form Core] `defaultValue` from field doesn't take precedence over form `defaultValues`
### Describe the bug

`defaultValue` from field doesn't take precedence over form `defaultValues`

### Your minimal, reproducible example

[Reproducible example](https://codesandbox.io/p/sandbox/tanstack-form-default-value-ns654m?file=/src/index.tsx:1,1)

### Steps to reproduce

1. Go to [Codesandbox](https://codesandbox.io/p/sandbox/tanstack-form-default-value-ns654m?file=/src/index.tsx:1,1)
2. See that the default value in the first name field is `João` instead of `Pedro`

### Expected behavior

I expected to see `Pedro` as the default value of the first name field

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

- OS: Linux
- Browser: Chrome
- Version: 115

### Tanstack Form adapter

vanilla

### TanStack Form version

v0.0.15

### TypeScript version

Latest (I guess)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by minosss**
Set the form's value when creating a field with defined default value.  Close #435

### CODE REVIEW

**Review by crutchcorn — APPROVED** [review]

**Comment by crutchcorn** [comment]
Thanks for this! Can you fix the merge conflicts and I can merge this in? 😊

**Comment by minosss** [comment]
Done

**Comment by crutchcorn** [comment]
Apologies - looks like format failed. Any chance you can run prettier over your new code? I would typically do this on behalf of contributors, but I'm knee-deep in Zod validator logic ATM

**Comment by minosss** [comment]
done

**Comment by crutchcorn** [comment]
Merged! Thanks so much for this contribution and your patience!

**Pull request merged**
