### PR TITLE
Comply with `react/no-children-prop` ESLint rule

### PR DESCRIPTION
**Pull request by rinarakaki**
Let’s do this before v1.

### CODE REVIEW

**Comment by Pascalmh** [comment]
This should be a stylistics choice. It was discussed before in the discord-channel: https://discord.com/channels/719702312431386674/1278341822883823626/1278342479879340146

@crutchcorn said:

`<Comp children={() => null} />`

is the same as:

`<Comp>{() => null}</Comp>`

> Just more shortform preference for us. It's a pretty minor change that doesn't impact speed or anything else

-----

Thad said: my personal preference would be to set the Eslint rule to `allowFunctions` (see https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md#allowfunctions)

**Comment by crutchcorn** [comment]
+1 to what @Pascalmh said. Nothing to add on my end. Closing per stylistic decision.

**Comment by rinarakaki** [comment]
Sorry, but

> Just more shortform preference for us

means @crutchcorn prefers this change, right?

**Comment by crutchcorn** [comment]
More or less.

**Pull request closed without merging**
