### PR TITLE
Upgrade and migrate Valibot to v0.31.0

### PR DESCRIPTION
**Pull request by fabian-hiller**
https://valibot.dev/guides/migrate-to-v0.31.0/

### CODE REVIEW

**Review by crutchcorn — APPROVED** [review]
This is awesome! Thanks so much for being an incredible library partner @fabian-hiller!

Just out of curiosity, when should we release this? I see you have an RC release in the PR right now, I think ideally we'd want to wait to merge until we have a `0.31` stable release?

What do you think? We'll follow your guidance here 100%.

**Comment by fabian-hiller** [comment]
This is perfect! I plan to release it in the next few days. I will post it on X. You will probably see it.

**Comment by fabian-hiller** [comment]
v0.31.0 is available: https://valibot.dev/blog/valibot-v0.31.0-is-finally-available/

**Comment by crutchcorn** [comment]
@fabian-hiller if you could resolve conflicts and update the packages to stable, we'll merge ASAP! :D

**Pull request merged**
