### PR TITLE
fix: handle numeric keys as array index only if parent is an array

### LINKED ISSUE #985: Record fields with numbers as keys does not work as excpected
### Describe the bug

I've added Record field, so, type looks like this
```typescript
interface FormType {
    items: Record<number, {quantity: number}>
}
``` 

Types in form work well, Field with name items.${number}.quantity works. 
So, items in state are {} and when I change quantity for item with 64, it replaces items value with [null, null, null, ..., 64]

I also discovered, that if record keys are strings(contains any non-numeric character), it works fine. 

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/zen-black-47s6fg?workspaceId=ca4463b1-f681-4a01-8bea-2aa832081a3a

### Steps to reproduce

To reproduce a bug with number keys
1. Run example
2. Change something in inputs
3. Press submit
4. Check console

To verify that it works with string keys
1. Uncomment next lines: `items: Record<string, { quantity?: number }>;`, `<form.Field key={item} name={\`items.item-${item}.quantity\`}>`
2. Comment next lines after uncommented
3. Change something in inputs
4. Press submit
5. Check console

### Expected behavior

Even if I use numeric keys, it should work as record, not create array. Probably it could be recognised from array fields by existing of []

### How often does this bug happen?

None

### Screenshots or Videos

_No response_

### Platform

-

### TanStack Form adapter

react-form

### TanStack Form version

v34.0

### TypeScript version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Balastrong**
Fixes #985

### CODE REVIEW

**Comment by Balastrong** [comment]
@maksymskuibida can you please validate that this fix works in your project?

You can try the version of this PR with
```
yarn add https://pkg.pr.new/@tanstack/react-form@993
```

**Comment by maksymskuibida** [comment]
> @maksymskuibida can you please validate that this fix works in your project?
> 
> You can try the version of this PR with
> 
> ```
> yarn add https://pkg.pr.new/@tanstack/react-form@993
> ```

I am sorry for late response. I just tested and it does not work. The same as it was before

**Comment by Balastrong** [comment]
@maksymskuibida on the code sandbox you provided it seems to be working (make sure to stop the dev server and run `yarn dev` again after installing the package)
I tried to [fork the demo](https://codesandbox.io/p/devbox/keen-zeh-s2pfqs) here.

If you have a more complete example where it's still broken please share it so I can give it another try :D

**Review by crutchcorn — APPROVED** [review]
If tests are passing, let's merge this. Don't let perfect be the enemy of better :)

**Pull request merged**
